### ISSUE TITLE
Publish new release on rubygems

### ISSUE THREAD

**Issue by alebedev** [devrandom/net_dav#33]
There have been many useful fixes since 0.5.0 published on Rubygems on March 12, 2010.
Could you bump version number and publish it?
Thanks!

**Comment by raymyers** [comment]
+1 for this. The latest code has features I'd like to use.

**Comment by duffyjp** [comment]
I forked the project today so I could install the current master via gem for a small ruby script.

https://github.com/duffyjp/net_dav

To get the gem, check out the project and run ```rake build```

The fork is basically a version bump with Jeweler replaced with Bundler.  I couldn't get Jeweler to play nice.

```
🌶  net_dav 14:41$ rake -T
rake build            # Build net_dav-0.5.1.gem into the pkg directory
rake clean            # Remove any temporary products
rake clobber          # Remove any generated files
rake install          # Build and install net_dav-0.5.1.gem into system gems
rake install:local    # Build and install net_dav-0.5.1.gem into system gems without network access
rake release[remote]  # Create tag v0.5.1 and build and push net_dav-0.5.1.gem to Rubygems
```

Note: Rubygems doesn't have this change as I don't have write access.  :)

**Comment by thomasfl** [comment]
@duffyjp excellent! Things have changed since net_dav was created. Would you care to make a pull request where jeweler has been replaced with bundler?

**Comment by duffyjp** [comment]
@thomasfl You bet!  I opened a PR this morning:   #36

**Comment by sr189** [comment]
+1 for a new release on rubygems. I'm glad to help if necessary.

Thank you!

**Comment by lelbarton** [comment]
+1 for me as well. I'd like to be able to run in Docker and doing a simple gem install on the image is preferable to cloning and building outside of that.

**Comment by thomasfl** [comment]
I tried to push the net_dav gem today, and got this error message.

````
thomasf@MacFlemming-2 net_dav (master) $ rake build
net_dav 0.5.1 built to pkg/net_dav-0.5.1.gem.
thomasf@MacFlemming-2 net_dav (master) $ gem push pkg/net_dav-0.5.1.gem 
Pushing gem to https://rubygems.org...
ERROR:  "https://rubygems.org" is not allowed by the gemspec, which only allows "TODO: Set to 'http://mygemserver.com'"
````

**Comment by sr189** [comment]
The `allowed_push_host` option in the gemspec is only necessary for private hosts. You should be able to just remove the if-else-block (line 18 to 22) from the gemspec and it should publish the gem on rubygems.org just fine.

**Comment by thomasfl** [comment]
Thanks a lot @sr189. The new gem has been pushed successfully today. :-)

````bash
  $ gem push pkg/net_dav-0.5.1.gem 
  Pushing gem to https://rubygems.org...
  Successfully registered gem: net_dav (0.5.1)
````

I am sorry that it has taken me so long to do this.
